#!/usr/bin/env bash
# Display information about subdomains

get_subdomain_info() {
    local domain=$1
    local subdomain=$2
    local result=$(dig "$subdomain.$domain" | grep -A1 'ANSWER SECTION:' | tail -1)
    local record_type=$(echo "$result" | awk '{print $4}')
    local destination=$(echo "$result" | awk '{print $5}')
    echo "The subdomain $subdomain is a $record_type record and points to $destination"
}

domain=$1
subdomain=$2

if [ -z "$subdomain" ]; then
    get_subdomain_info "$domain" "www"
    get_subdomain_info "$domain" "lb-01"
    get_subdomain_info "$domain" "web-01"
    get_subdomain_info "$domain" "web-02"
else
    get_subdomain_info "$domain" "$subdomain"
fi
